swagger: "2.0"
info:
  description: "위성영상 시각화 웹 서비스를 위한 Swagger"
  version: "1.0.0"
  title: "Satellite Visualization Test"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "parkth32@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:3000"
basePath: "/"
tags:
- name: "object"
  description: "객체 식별 정보"
- name: "compare"
  description: "변화 탐지 정보"
schemes:
- "http"
paths:
  /object/objects:
    get:
      tags:
      - "object"
      summary: "분석한 모든 객체 리스트"
      description: ""
      operationId: "objects"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "Success"
          schema:
            type: "array"
            items: 
              type: "string"
            default:
              - "자동차"
              - "비행기"
              - "선박"
        "304":
          description: "Same Data"
        "404":
          description: "Not found"
  /object/{object}/date:
    get:
      tags:
      - "object"
      summary: "변화 탐지한 날짜"
      description: ""
      operationId: "getObjectDate"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: object
        in: path
        description: "대상 객체"
        required: true
        type: string
      responses:
        "200":
          description: "Success"
          schema:
            type: "array"
            items: 
              type: "string"
            default:
              - "20210122"
              - "20210123"
        "304":
          description: "Same Data"
        "404":
          description: "Not found"             
  /object/map/{date}/{object}:
    get:
      tags:
      - "object"
      summary: "분석한 위성 사진"
      description: ""
      operationId: "getObjectImage"
      consumes:
      - "application/json"
      produces:
        - image/png
      parameters:
      - name: date
        in: path
        description: "촬영 날짜"
        required: true
        type: string
      - name: object
        in: path
        description: "식별 객체"
        required: true
        type: string
      responses:
        "200":
          description: "Success (PNG 이미지를 데이터로 받음)"
        "304":
          description: "Same Data"
  /object/info/{date}/{object}:
    get:
      tags:
      - "object"
      summary: "위성 사진 분석 정보"
      description: ""
      operationId: "getObjectInfo"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: date
        in: path
        description: "촬영 날짜"
        required: true
        type: string
      - name: object
        in: path
        description: "식별 객체"
        required: true
        type: string
      responses:
        "200":
          description: "Success"
          schema:
            type: object
            properties:
              extent:
                type: array
                items: 
                  type: string
                default: [127.3, 30.5, 127.5, 30.8]
              geojson:
                type: object
                default: {"foo":"bar"}
  /compare/date:
    get:
      tags:
      - "compare"
      summary: "변화 탐지한 날짜"
      description: ""
      operationId: "getCompareDate"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "Success"
          schema:
            type: "array"
            items: 
              type: "string"
            default:
              - "20210122"
              - "20210123"
        "304":
          description: "Same Data"
        "404":
          description: "Not found"    
  /compare/map/{date_from}/{date_to}/from:
    get:
      tags:
      - "compare"
      summary: "변화 탐지 사진"
      description: ""
      operationId: "getFromMap"
      consumes:
      - "application/json"
      produces:
      - image/png
      parameters:
      - name: date_from
        in: path
        description: "변화 탐지를 위한 이전 날짜"
        required: true
        type: string
      - name: date_to
        in: path
        description: "변화 탐지를 위한 이후 날짜"
        required: true
        type: string
      responses:
        "200":
          description: "Success (PNG 이미지를 데이터로 받음)"
        "404":
          description: "Not found"
  /compare/map/{date_from}/{date_to}/to:
    get:
      tags:
      - "compare"
      summary: "변화 탐지 사진"
      description: ""
      operationId: "getToMap"
      consumes:
      - "application/json"
      produces:
      - image/png
      parameters:
      - name: date_from
        in: path
        description: "변화 탐지를 위한 이전 날짜"
        required: true
        type: string
      - name: date_to
        in: path
        description: "변화 탐지를 위한 이후 날짜"
        required: true
        type: string
      responses:
        "200":
          description: "Success (PNG 이미지를 데이터로 받음)"        
        "404":
          description: "Not found"         
  /compare/info/{date_from}/{date_to}:
    get:
      tags:
      - "compare"
      summary: "변화 탐지 정보"
      description: ""
      operationId: "getCompareImage"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: date_from
        in: path
        description: "변화 탐지를 위한 이전 날짜"
        required: true
        type: string
      - name: date_to
        in: path
        description: "변화 탐지를 위한 이후 날짜"
        required: true
        type: string
      responses:
        "200":
          description: "Success"
          schema:
            type: object
            properties:
              extent1:
                type: array
                items: 
                  type: string
                default: [127.3, 30.5, 127.5, 30.8]
              extent2:
                type: array
                items: 
                  type: string
                default: [127.2, 30.4, 127.6, 30.9]
              geojson:
                type: object
                default: {"foo":"bar"}
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"